Anchor-Protocol/anchor-web-app

app/public/fonts/gotham.css, app/public/index.html, app/src/env.ts, base/src/base/env.ts
This PR fixes some of the UI glitches in certain environments.
- fix gotham.css to point to the correct path
- fix gotham book variants
=> fix: gotham mime type

app/src/components/Header/WalletSelector/AirdropContent.tsx, app/src/components/Header/WalletSelector/index.tsx, app/src/pages/send/transactions/sendOptions.ts, app/src/pages/send/useSendDialog.tsx, base/src/base/AppProviders.tsx
=> Feature:  Memo

app/src/components/Header/DesktopHeader.tsx, app/src/components/Header/MobileHeader.tsx, app/src/components/TransactionRenderer/Fault.tsx, app/src/pages/gov/components/Rewards.tsx, packages/src/@terra-dev/broadcastable-operation/context/OperationBroadcaster.tsx, packages/src/@terra-dev/broadcastable-operation/context/types.ts, packages/src/@terra-dev/broadcastable-operation/context/useOperation.ts
=> Feature: error message

app/src/components/Header/MobileHeader.tsx, app/src/components/Header/WalletSelector/AirdropContent.tsx, app/src/components/Header/WalletSelector/AirdropImage.tsx, app/src/components/Header/WalletSelector/index.tsx
=> Feature: Airdrop dialog on mobile layout

app/src/@anchor-protocol/webapp-fns/env.ts
point to official api endpoints that support bETH
=> fix: point to official api endpoints

app/src/@anchor-protocol/webapp-fns/env.ts, app/src/@anchor-protocol/webapp-fns/tx/airdrop/claim.ts, app/src/pages/airdrop/index.tsx
- multiplied 2.54x to all fixedGas (0.25 -> 0.38)
=> [WIP] fix: update min gas price of 0.38uusd

app/src/pages/dashboard/components/ANCPriceChart.tsx, app/src/pages/dashboard/components/CollateralsChart.tsx, app/src/pages/dashboard/components/StablecoinChart.tsx, app/src/pages/dashboard/components/TotalValueLockedDoughnutChart.tsx, app/src/pages/mypage/components/graphics/DoughnutGraph.tsx, app/src/pages/trade/components/AncUstLpProvide.tsx, app/src/pages/trade/components/AncUstLpWithdraw.tsx, app/src/pages/trade/components/TradeBuy.tsx
=> fix: check side effects for gas_price changed

app/.storybook/preview.js
- fixed `ReferenceError: React is not defined` issue with component stories
=> fixed missing import

app/src/components/dialogs/useReadonlyWalletDialog.tsx
Adds a small ux patch that allows users to use enter key to submit the "View an address" form
=> Allow enter key to submit "View an address"

app/src/components/Header/mobile/MobileHeader.tsx
=> [Bugfix] Mobile header styles.

app/src/pages/earn/components/AmountSlider/index.tsx
=> [Bugfix] AmountSlider txFee issue.

app/src/@anchor-protocol/app-fns/queries/borrow/apy.ts, app/src/pages/gov/components/Overview/index.tsx, app/src/pages/mypage/components/Rewards.tsx
=> Move ANC-UST LP APR to fetch from Astro.

app/src/@anchor-protocol/app-fns/queries/borrow/__tests__/borrowAPY.test.ts, app/src/@anchor-protocol/app-fns/queries/borrow/apy.ts, app/src/@anchor-protocol/app-provider/queries/borrow/apy.ts
=> Optimize astro LP APR query to fetch single item instead.

app/src/@anchor-protocol/app-fns/logics/borrow/computeEstimateLiquidationPrice.ts, app/src/@anchor-protocol/app-fns/logics/borrow/computeLiquidationPrice.ts, app/src/@anchor-protocol/app-fns/queries/borrow/apy.ts, app/src/@anchor-protocol/app-fns/tx/basset/import.ts, app/src/pages/borrow/components/CollateralList.tsx, app/src/utils/microfyPrice.ts
=> [Bugfix] Fix liquidation price formatting.

app/src/@anchor-protocol/formatter/types.ts, app/src/@anchor-protocol/formatter/useFormatters.ts, app/src/@libs/evm-wallet/providers/EvmWalletProvider.tsx, app/src/@libs/evm-wallet/types.ts, app/src/components/BuyButton.tsx, app/src/components/Header/DesktopHeader.tsx, app/src/components/Header/mobile/MobileHeader.tsx, app/src/components/Header/wallet/TokenList.tsx, app/src/components/Header/wallet/evm/Content.tsx, app/src/components/Header/wallet/evm/WithdrawableAsset.tsx, app/src/components/Header/wallet/evm/WithdrawableAssets.tsx
Added in the _Add to Wallet_ button and also modified the look of the withdraw assets button.
=> added in the add to metamask button

app/src/pages/terms/assets/tos2.md
=> Update ToS "Contacting us" section.

app/src/@anchor-protocol/app-provider/contexts/target.tsx
=> Add Terra as a default chain of choice in case a undefined value is read from storage.

app/package.json, app/src/components/Footer/index.tsx, app/src/pages/terms/index.tsx
=> Show latest git commit hash in the footer

app/src/pages/dashboard/index.tsx
=> Add ANC price fallback to terraswap ANC price in case indexer fails.

app/src/pages/gov/poll.create.modify-collateral-attribute.tsx
=> Allow user to choose any whitelist collateral

app/src/pages/dashboard/components/ANCPriceChart.tsx, app/src/pages/dashboard/components/internal/axisUtils.ts, app/src/pages/dashboard/index.tsx
=> Hotfix: ANC chart x-labels overflow

app/index.html, app/src/pages/dashboard/index.tsx, app/vite.config.ts, landing/package.json, landing/public/index.html, yarn.lock
Added animate number animation to ANC price as well.
=> [Fix] Google search engine results display.

app/src/pages/dashboard/index.tsx, app/src/pages/mypage/components/TotalClaimableRewards.tsx, app/src/pages/mypage/logics/useRewards.ts
=> Include ASTRO rewards in the "Total Claimable" card

app/src/pages/mypage/components/TotalClaimableRewards.tsx
=> [Bugfix] Filter zero price from claim all rewards.

app/src/pages/mypage/components/TotalClaimableRewards.tsx
=> Hide price too when reward is zero.

app/src/pages/mypage/components/TotalClaimableRewards.tsx
=> Show ANC price always on mypage-claim rewards, even if no rewards exist.

app/src/configurations/app.tsx
Necessary for the IPFS site to properly route links.
https://app.anchorprotocol.com/borrow –> https://app.anchorprotocol.com/#/borrow
=> fix: Use HashRouter

.github/workflows/cicd.yml
Use Route53 instead of CloudFlare
=> ci: Update Route53 DNSLink with IPFS CID
